### ISSUE TITLE
EOFError while reading using baseband

### ISSUE THREAD

**Issue by tcassanelli** [mhvk/scintillometry#145]
I am having trouble reading data while using `scintillometry` and `baseband`. I am not sure whether the error is in one or the other, but I have my suspicions that it is the former.
**Note** that for previous versions of both softwares the package ran fine with the same dataset.

My software basically wraps the functions for reading and changing shape (`ChangeSampleShape`), these are:

```python 
def telescope_shape(fh, telescope):
    """
    Reshape data for ARO or CHIME with a file handler. This is the standard way
    to transform data to V[time, frequency, polarization]. ``A = CHIME`` and
    ``B = ARO``.

    Parameters
    ----------
    fh : `baseband.vdif.base.VDIFStreamReader`
        File-handler from `baseband`.
    telescope : `str`:
        Telescope name: ``'CHIME'`` or ``'ARO'``.

    Returns
    -------
    fh_reshaped : `baseband.vdif.base.VDIFStreamReader`
        File-handler with the new shape.
    """

    def reshape_chime(data):
        return data.reshape(-1, 256, 4, 2).transpose(
            0, 2, 1, 3).reshape(-1, 1024, 2)

    def reshape_aro(data):
        return data.swapaxes(1, 2)

    if telescope == 'CHIME' or telescope == 'A':
        fh_reshaped = ChangeSampleShape(fh, reshape_chime)

    elif telescope == 'ARO' or telescope == 'B':
        fh_reshaped = ChangeSampleShape(fh, reshape_aro)

    return fh_reshaped
```

and

```python
def read_ntime(
    data_sorted, telescope, timestamp_i, ntime, freq_resolution=390625 * u.Hz,
    verify=True
        ):

    """
    Given an initial timestamp, ``timestamp_i``, read the following ``ntime``
    number of samples that follow.

    Parameters
    ----------
    data_sorted : `list`
        List of strings with the corresponding paths of files to be opened.
        Files must be sorted chronologically.
    telescope : `str`:
        Telescope name: ``'CHIME'`` or ``'ARO'``.
    timestamp_i : `astropy.time.core.Time`
        Initial timestamp from where to start reading.
    ntime : `int`
        Number of time samples of `2.56e-6` s to be opened.
    freq_resolution : `int`
        Frequency resolution, sample rate or frequency sampling in
        math:`\\mathrm{Hz}`.
    verify : `bool`
        Whether to do consistency checks on frames being read. See `baseband`
        reference. It is set default `True`.

    Returns
    -------
    V : `np.ndarray`
        Three-dimension array, shaped as ``V[ntime, frequency, polarization]``.
    limits: `list`
        List containing the `astropy.time.core.Time` of start and stop of
        `data_sorted`.
    """

    fraw = helpers.sequentialfile.open(data_sorted, 'rb')
    fh = vdif.open(fraw, mode='rs', sample_rate=freq_resolution, verify=verify)
    fh = telescope_shape(fh, telescope=telescope)

    fh.seek(timestamp_i)

    # updating timestamp with baseband
    timestamp_i_corrected = fh.tell(unit='time')

    V = fh.read(ntime)

    # checking whether the timestamp is in the sequence
    timestamp_f = fh.tell(unit='time')
    if fh.stop_time < timestamp_f:
        pass
    else:
        timestamp_f = fh.stop_time

    fh.close()

    limits = [timestamp_i_corrected, timestamp_f]

    return V, limits
```

While running my GP-search I encounter the same error over and over, until it ran through all the data set.

```bash
Traceback (most recent call last):
  File "/home/v/vanderli/cassane/babendil-frb-vlbi/scripts/gp_run_search.py", line 184, in <module>
    gp_thres=gp_thres
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/babendil-0.0.1-py3.7.egg/babendil/sigprocess/gp_search.py", line 298, in run
    V_cdd, limits = self.process_file(timestamp, ntime)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/babendil-0.0.1-py3.7.egg/babendil/sigprocess/gp_search.py", line 207, in process_file
    verify=False
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/babendil-0.0.1-py3.7.egg/babendil/io/reader.py", line 172, in read_ntime
    V = fh.read(ntime)
  File "/home/v/vanderli/cassane/anaconda3/lib/python3.7/site-packages/scintillometry-0.0.dev394-py3.7.egg/scintillometry/base.py", line 298, in read
    raise EOFError("cannot read from beyond end of input.")
EOFError: cannot read from beyond end of input.
```

Located here:

https://github.com/mhvk/scintillometry/blob/e8464747599574b0a61aa662f28289c9bbbcfc03/scintillometry/base.py#L296-L298

Some other comments: 
* I set `verify=False`
* Tested random timestamps and it seems to give the same problem over and over

**Comment by tcassanelli** [comment]
I looked in more detail opening several lengths of frame number (`ntime` in my notation), and seems like the problem is in `baseband`? I am getting the same error Hsiu-Hsien, I think.

```
In [21]: V, limits = babendil.io.read_ntime(data_sorted, telescope='CHIME', timestamp_i=ti
    ...: mestamp, ntime=2 ** 12)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-fe323688bcd7> in <module>
----> 1 V, limits = babendil.io.read_ntime(data_sorted, telescope='CHIME', timestamp_i=timestamp, ntime=2 ** 12)

~/anaconda3/lib/python3.7/site-packages/babendil-0.0.1-py3.7.egg/babendil/io/reader.py in read_ntime(data_sorted, telescope, timestamp_i, ntime, freq_resolution, verify)
    170     timestamp_i_corrected = fh.tell(unit='time')
    171
--> 172     V = fh.read(ntime)
    173
    174     # checking whether the timestamp is in the sequence

~/anaconda3/lib/python3.7/site-packages/scintillometry-0.0.dev394-py3.7.egg/scintillometry/base.py in read(self, count, out)
    309                 # that _read_frame can count on tell() being correct.
    310                 self.offset = frame_index * self._samples_per_frame
--> 311                 self._frame = self._read_frame(frame_index)
    312                 self._frame_index = frame_index
    313

~/anaconda3/lib/python3.7/site-packages/scintillometry-0.0.dev394-py3.7.egg/scintillometry/base.py in _read_frame(self, frame_index)
    557         # Read data from underlying filehandle.
    558         self.ih.seek(frame_index * self._raw_samples_per_frame)
--> 559         data = self.ih.read(self._raw_samples_per_frame)
    560         # Apply function to the data.  Note that the read() function
    561         # in base ensures that our offset pointer is correct.

~/anaconda3/lib/python3.7/site-packages/baseband-3.0.dev1076-py3.7.egg/baseband/vlbi_base/base.py in read(self, count, out)
    786                                                 self.samples_per_frame)
    787             if frame_index != self._frame_index:
--> 788                 self._frame = self._read_frame(frame_index)
    789                 self._frame.fill_value = self.fill_value
    790                 self._frame_index = frame_index

~/anaconda3/lib/python3.7/site-packages/baseband-3.0.dev1076-py3.7.egg/baseband/vlbi_base/base.py in _read_frame(self, index)
    838         if frame_index != index:
    839             return self._bad_frame(index, frame,
--> 840                                    ValueError('wrong frame number.'))
    841
    842         # In either case, we check the next frame (if there is one).

~/anaconda3/lib/python3.7/site-packages/baseband-3.0.dev1076-py3.7.egg/baseband/vdif/base.py in _bad_frame(self, index, frameset, exc)
    535
    536         if self.verify != 'fix':
--> 537             raise exc
    538
    539         msg = 'problem loading frame set {}.'.format(index)

ValueError: wrong frame number.
```

**Comment by mhvk** [comment]
@tcassanelli - I think you may indeed be running into the same problem as Hsiu-Hsien; but in the above, I think you are using `verify=True`, correct?

(you really should use `verify=False` only if you *know* the data set is correct!)

**Comment by tcassanelli** [comment]
oops yes that is correct, my bad. If I correct that then it get's to the same error as Hsiu-Hsien has (same as this data set https://github.com/mhvk/baseband/issues/338#issuecomment-576488011).

**Comment by mhvk** [comment]
OK, thanks. Will close this issue, since it clearly is due to baseband, not scintillometry....
